DATA:
  DATASET: agiqa20k
  BATCH_SIZE: 32 
  PATCH_NUM: 15 
  DATA_PATH: '/home/data1/lq/IQA_datasets/aigiqa30k'
  NUM_WORKERS: 8
  PIN_MEMORY: True
  CROP_SIZE: 224
  #COUNT: 1162
SET:
  COUNT: 20000
MODEL:
  TYPE: deiqt
  NAME: production
  DROP_PATH_RATE: 0.0
  VIT:
    PATCH_SIZE: 16
    EMBED_DIM: 384
    DEPTH: 12
    NUM_HEADS: 6
    MLP_RATIO: 4
    QKV_BIAS: True
    # Download the pretrained weights and input the path here
    PRETRAINED: True
    PRETRAINED_MODEL_PATH: /home/Newdisk/lq/My-IQA/deit_3_small_224_21k.pth
    CROSS_VALID: False
    CROSS_MODEL_PATH: /home/Newdisk/lq/My-IQA/deit_3_small_224_21k.pth
    N_MODELS: 3
TRAIN:
  EPOCHS: 150
  WARMUP_EPOCHS: 3
  WEIGHT_DECAY: 0.001  #0.05   0.001是按照IPCE改的
  BASE_LR: 5.0e-6  #1.0e-5
  #BASE_LR: 2.0e-4
  WARMUP_LR: 2.0e-6
  MIN_LR: 1.0e-6
  OPTIMIZER:
    NAME: 'adamw'
    EPS: 1e-8
    BETAS: 0.9
    BETAS2: 0.999
    MOMENTUM: 0.9
  LR_SCHEDULER:
    NAME: step
    DECAY_EPOCHS: 3
    DECAY_RATE: 0.1
  ACCUMULATION_STEPS: 1
  CLIP_GRAD: 5.0
DISABLE_SAVE: True
AMP_ENABLE: True