DATA:
  DATASET: aigciqa2023
  BATCH_SIZE: 12 
  PATCH_NUM: 15 
  DATA_PATH: '/home/data1/lq/IQA_datasets/AIGCIQA2023'
  NUM_WORKERS: 8
  PIN_MEMORY: True
  CROP_SIZE: 224
  #COUNT: 1162
SET:
  COUNT: 2400
TRAIN:
  EPOCHS: 150
  WARMUP_EPOCHS: 3
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.0e-5
  #BASE_LR: 2.0e-4
  WARMUP_LR: 2.0e-6
  MIN_LR: 1.0e-5
  OPTIMIZER:
    NAME: 'adamw'
    EPS: 1e-8
    BETAS: 0.9
    BETAS2: 0.999
    MOMENTUM: 0.9
  LR_SCHEDULER:
    NAME: step
    DECAY_EPOCHS: 3
    DECAY_RATE: 0.1
  ACCUMULATION_STEPS: 1
  CLIP_GRAD: 5.0
DISABLE_SAVE: True
AMP_ENABLE: True
